import type { Metadata } from "next";
import "~/style/global.scss"
import { Header } from "~/components/Header/header";

export const metadata: Metadata = {
  title: "Megaline",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className="dark">
      <Header />
        {children}
        </body>
    </html>
  );
}
